export type GalleryCategory = "corporate" | "model";

export type Photo = {
  id: string;
  src: string;
  alt: string;
  category: GalleryCategory;
};

// Display order of the category filter buttons.
export const galleryCategories: GalleryCategory[] = ["corporate", "model"];

export const photos: Photo[] = [
  { id: "JOY09696", src: "/media/Corporate/coreporate64.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "JOY09746", src: "/media/Corporate/coreporate65.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "JOY09895", src: "/media/Corporate/coreporate66.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "JOY09945", src: "/media/Corporate/coreporate67.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "KHN-0809", src: "/media/Corporate/coreporate68.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "KHN-1181", src: "/media/Corporate/coreporate69.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "RED00288", src: "/media/Corporate/coreporate70.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "RED00938", src: "/media/Corporate/coreporate71.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "REH00030", src: "/media/Corporate/coreporate72.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "REH00058", src: "/media/Corporate/coreporate73.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "REH09647", src: "/media/Corporate/coreporate74.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "JOY09707", src: "/media/Corporate/coreporate75.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "JOY09759", src: "/media/Corporate/coreporate76.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "JOY09937", src: "/media/Corporate/coreporate77.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "JOY09948", src: "/media/Corporate/coreporate78.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "JOY09986", src: "/media/Corporate/coreporate81.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "KKK-2712", src: "/media/Corporate/coreporate82.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "KKK-2738", src: "/media/Corporate/coreporate83.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "RED00278", src: "/media/Corporate/coreporate84.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "RED00977", src: "/media/Corporate/coreporate85.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "RED01273", src: "/media/Corporate/coreporate86.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "RED02488", src: "/media/Corporate/coreporate87.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "RED02950", src: "/media/Corporate/coreporate88.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "REH00085", src: "/media/Corporate/coreporate89.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "REH00274", src: "/media/Corporate/coreporate90.JPEG", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-C95B1570", src: "/media/Events/C95B1570.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-C95B1814", src: "/media/Events/C95B1814.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-C95B5892", src: "/media/Events/C95B5892.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-C95B5907", src: "/media/Events/C95B5907.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-C95B5961", src: "/media/Events/C95B5961.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-C95B6812", src: "/media/Events/C95B6812.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-C95B7711", src: "/media/Events/C95B7711.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-C95B7758", src: "/media/Events/C95B7758.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-C95B9148", src: "/media/Events/C95B9148.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-C95B9242", src: "/media/Events/C95B9242.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC00488", src: "/media/Events/DSC00488.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03026", src: "/media/Events/DSC03026.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03039", src: "/media/Events/DSC03039.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03041", src: "/media/Events/DSC03041.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03046", src: "/media/Events/DSC03046.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03047", src: "/media/Events/DSC03047.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03071", src: "/media/Events/DSC03071.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03072", src: "/media/Events/DSC03072.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03073", src: "/media/Events/DSC03073.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03077", src: "/media/Events/DSC03077.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03405", src: "/media/Events/DSC03405.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03409", src: "/media/Events/DSC03409.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03449", src: "/media/Events/DSC03449.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03451", src: "/media/Events/DSC03451.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03457", src: "/media/Events/DSC03457.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03484", src: "/media/Events/DSC03484.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03494", src: "/media/Events/DSC03494.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03663", src: "/media/Events/DSC03663.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03853", src: "/media/Events/DSC03853.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03872", src: "/media/Events/DSC03872.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03948", src: "/media/Events/DSC03948.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03951", src: "/media/Events/DSC03951.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC03961", src: "/media/Events/DSC03961.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC04004", src: "/media/Events/DSC04004.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC04151", src: "/media/Events/DSC04151.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC04188", src: "/media/Events/DSC04188.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC04237", src: "/media/Events/DSC04237.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC04328", src: "/media/Events/DSC04328.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC04362", src: "/media/Events/DSC04362.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC05667", src: "/media/Events/DSC05667.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC05757", src: "/media/Events/DSC05757.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC05758", src: "/media/Events/DSC05758.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC06307", src: "/media/Events/DSC06307.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC06308", src: "/media/Events/DSC06308.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC06310", src: "/media/Events/DSC06310.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC06328", src: "/media/Events/DSC06328.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC06332", src: "/media/Events/DSC06332.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC06348", src: "/media/Events/DSC06348.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC06352", src: "/media/Events/DSC06352.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC08172", src: "/media/Events/DSC08172.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC08203", src: "/media/Events/DSC08203.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC08205", src: "/media/Events/DSC08205.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC08265", src: "/media/Events/DSC08265.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC08317", src: "/media/Events/DSC08317.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC08388", src: "/media/Events/DSC08388.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC08436", src: "/media/Events/DSC08436.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC08568", src: "/media/Events/DSC08568.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC08649", src: "/media/Events/DSC08649.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-DSC08962", src: "/media/Events/DSC08962.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-KKK_2733", src: "/media/Events/KKK_2733.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-KKK_3583", src: "/media/Events/KKK_3583.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-REH00046", src: "/media/Events/REH00046.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-REH00047", src: "/media/Events/REH00047.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-REH00195", src: "/media/Events/REH00195.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "EV-REH09814", src: "/media/Events/REH09814.jpg", alt: "Corporate event photo", category: "corporate" },
  { id: "Model1", src: "https://i.ibb.co/qYZ92V6w/Model1.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model12", src: "https://i.ibb.co/k2y0jp0X/Model12.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model13", src: "https://i.ibb.co/n8KVC1t4/Model13.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model14", src: "https://i.ibb.co/7JPpXyD1/Model14.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model15", src: "https://i.ibb.co/BVrpPrWt/Model15.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model16", src: "https://i.ibb.co/fVpR0d5r/Model16.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model17", src: "https://i.ibb.co/Pv2SP5RY/Model17.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model18", src: "https://i.ibb.co/0VKsjbD8/Model18.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model19", src: "https://i.ibb.co/gbf1B8Lk/Model19.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model20", src: "https://i.ibb.co/hGYzkx8/Model20.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model21", src: "https://i.ibb.co/KpjfhPj1/Model21.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model22", src: "https://i.ibb.co/pvz2txYp/Model22.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model23", src: "https://i.ibb.co/VWvqqFpw/Model23.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model24", src: "https://i.ibb.co/fY2GJm33/Model24.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model25", src: "https://i.ibb.co/KcZp8RWd/Model25.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model26", src: "https://i.ibb.co/yn066QDv/Model26.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model27", src: "https://i.ibb.co/gbkyFJL0/Model27.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model28", src: "https://i.ibb.co/tRpmDHY/Model28.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model29", src: "https://i.ibb.co/LhszgXf9/Model29.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model31", src: "https://i.ibb.co/BHkrSjwd/Model31.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model32", src: "https://i.ibb.co/Z1tLQymN/Model32.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model34", src: "https://i.ibb.co/DDvgRJRm/Model34.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model35", src: "https://i.ibb.co/Q7MyC7p6/Model35.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model36", src: "https://i.ibb.co/ccM1x8cp/Model36.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model37", src: "https://i.ibb.co/F2bJ6nF/Model37.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model38", src: "https://i.ibb.co/4ZJHc9GR/Model38.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model39", src: "https://i.ibb.co/60qcdcs8/Model39.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model40", src: "https://i.ibb.co/wr8bwHYs/Model40.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model41", src: "https://i.ibb.co/Wv1ZQQTB/Model41.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model42", src: "https://i.ibb.co/23ScFBwB/Model42.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model43", src: "https://i.ibb.co/TBg6wXrz/Model43.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model44", src: "https://i.ibb.co/XrH0c30T/Model44.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model45", src: "https://i.ibb.co/7xmhM0s1/Model45.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model46", src: "https://i.ibb.co/8nHzDPhn/Model46.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model47", src: "https://i.ibb.co/qLh6cL7s/Model47.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model48", src: "https://i.ibb.co/zT7K4Cg6/Model48.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model49", src: "https://i.ibb.co/dsMyXqP5/Model49.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model50", src: "https://i.ibb.co/gbSFtgH7/Model50.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model51", src: "https://i.ibb.co/m5ThspK8/Model51.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model52", src: "https://i.ibb.co/Y4kBm25T/Model52.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model53", src: "https://i.ibb.co/MDnbgW30/Model53.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model54", src: "https://i.ibb.co/FbgdN5GR/Model54.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model55", src: "https://i.ibb.co/dsjxn8XG/Model55.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model56", src: "https://i.ibb.co/BKsdvZLJ/Model56.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model57", src: "https://i.ibb.co/yn60cP1b/Model57.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model58", src: "https://i.ibb.co/xK4x7zXr/Model58.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model59", src: "https://i.ibb.co/XxRP5z2z/Model59.jpg", alt: "Model portfolio photo", category: "model" },
  { id: "Model60", src: "https://i.ibb.co/JjvyppXn/Model60.jpg", alt: "Model portfolio photo", category: "model" },
];

export function getPhotosByCategory(category: GalleryCategory): Photo[] {
  return photos.filter((photo) => photo.category === category);
}
